FROM    ubuntu:latest
LABEL	maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV	DEBIAN_FRONTEND="noninteractive"

COPY    bootstrap.sh /bootstrap.sh

RUN     apt-get -y update && apt -y upgrade \
        && apt-get install -y --no-install-recommends ca-certificates software-properties-common \
        && add-apt-repository -y ppa:ondrej/apache2 && add-apt-repository -y ppa:ondrej/php \
        && apt-get -y update && apt-get -y upgrade \
        && apt install -y nullmailer mailutils \
        && apt install -y --no-install-recommends apache2 apache2-utils

RUN     apt install -y --no-install-recommends \
		php8.0 php8.0-igbinary php-imagick php8.0-redis php8.0-mysql \
                php8.0-bcmath php8.0-cli php8.0-curl php8.0-dom php8.0-fpm php8.0-gd \
		php8.0-json php8.0-mbstring php8.0-mysql php8.0-opcache \
                php8.0-readline php8.0-soap php8.0-xml php8.0-zip php8.0-tidy php-apcu php-pgsql

RUN	apt-get -y purge software-properties-common unattended-upgrades apt-utils \
        && apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* \
        && rm -rf /etc/php/5.6 /etc/php/7.0 /etc/php/7.1 /etc/php/7.2 /etc/php/7.3 /etc/php/7.4 \
	&& cd /usr/lib/php && rm -rf 20131226 20151012 20160303 20170718 20180731 20190902 \
        && chmod +x /bootstrap.sh \
	&& a2enmod proxy_fcgi setenvif rewrite expires headers remoteip \
	&& a2enconf php8.0-fpm \
	&& a2dismod status \
        && mv /etc/apache2 /etc/apache2.orig && mkdir -p /etc/apache2 \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer \
        && dpkg-statoverride --update --add root adm 0000 /usr/bin/sudo \
        && dpkg-statoverride --update --add root adm 0000 /bin/su 

RUN     sh -x \
        && for user in `awk -F: '($3 < 1000) {print $1 }' /etc/passwd`; do \
          if [ $user != "root" ]; then \
            usermod -L $user && usermod -s /usr/sbin/nologin $user ;\
          fi ;\
        done

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

