# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/apache-phpfpm for a recent one

FROM    eilandert/php-fpm:8.1
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
COPY    bootstrap.sh /bootstrap.sh
COPY	conf-available /tmp/conf-available

RUN apt-get -y update ;\
    apt-get install -y --no-install-recommends apache2 apache2-utils libjemalloc2 mimalloc ;\
    apt-get -y autoremove ;\
    apt-get -y clean ;\
    apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN a2dismod status mpm_prefork ;\
    a2enmod mpm_event proxy_fcgi setenvif rewrite expires headers remoteip ;\
    cp /tmp/conf-available/php${PHPVERSION}-fpm.conf /etc/apache2/conf-available ;\
    a2enconf php${PHPVERSION}-fpm

RUN mv /etc/apache2 /etc/apache2.orig ;\
    mv /etc/nullmailer /etc/nullmailer.orig ;\
    mkdir -p /etc/apache2 ;\
    mkdir -p /etc/php ;\
    mkdir -p /etc/nullmailer ;\
    chmod +x /bootstrap.sh

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

