FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV	PHPVERSION=0
ENV	MODE=multi
ENV	TZ=Europe/Amsterdam

COPY    bootstrap.sh /bootstrap.sh

RUN     . /etc/os-release \
        && chmod +x /bootstrap.sh \
        && echo "deb [trusted=yes] http://ppa.launchpad.net/eilander/apache2/ubuntu ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/eilander-ubuntu-apache2-${UBUNTU_CODENAME}.list \
        && echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-${UBUNTU_CODENAME}.list \
        && apt-get -y update && apt-get -y upgrade \
        && apt-get install -y nullmailer mailutils \
        && apt-get install -y --no-install-recommends apache2 apache2-utils \
        && a2enmod proxy_fcgi setenvif rewrite expires headers remoteip \
        && a2dismod status \
        && apt-get -y autoremove && apt-get -y autoclean 

ENV	PHPVERSION=5.6
RUN     apt-get install -y --no-install-recommends \
                php${PHPVERSION} \
                php${PHPVERSION}-fpm \
                php${PHPVERSION}-apcu \
                php${PHPVERSION}-bcmath \
                php${PHPVERSION}-cli \
                php${PHPVERSION}-curl \
                php${PHPVERSION}-dom \
                php${PHPVERSION}-gd \
                php${PHPVERSION}-igbinary \
                php${PHPVERSION}-imagick \
                php${PHPVERSION}-json \
                php${PHPVERSION}-memcached \
                php${PHPVERSION}-mbstring \
                php${PHPVERSION}-mcrypt \
                php${PHPVERSION}-mysql \
                php${PHPVERSION}-opcache \
                php${PHPVERSION}-pgsql \
                php${PHPVERSION}-readline \
                php${PHPVERSION}-recode \
                php${PHPVERSION}-redis \
                php${PHPVERSION}-soap \
                php${PHPVERSION}-tidy \
                php${PHPVERSION}-xml \
                php${PHPVERSION}-zip \
        && apt-get -y autoremove && apt-get -y autoclean

ENV     PHPVERSION=7.2
RUN     apt-get install -y --no-install-recommends \
                php${PHPVERSION} \
                php${PHPVERSION}-fpm \
                php${PHPVERSION}-apcu \
                php${PHPVERSION}-bcmath \
                php${PHPVERSION}-cli \
                php${PHPVERSION}-curl \
                php${PHPVERSION}-dom \
                php${PHPVERSION}-gd \
                php${PHPVERSION}-igbinary \
                php${PHPVERSION}-imagick \
                php${PHPVERSION}-json \
                php${PHPVERSION}-memcached \
                php${PHPVERSION}-mbstring \
#               php${PHPVERSION}-mcrypt \
                php${PHPVERSION}-mysql \
                php${PHPVERSION}-opcache \
                php${PHPVERSION}-pgsql \
                php${PHPVERSION}-readline \
                php${PHPVERSION}-recode \
                php${PHPVERSION}-redis \
                php${PHPVERSION}-soap \
                php${PHPVERSION}-tidy \
                php${PHPVERSION}-xml \
                php${PHPVERSION}-zip \
	&& apt-get -y autoremove && apt-get -y autoclean


ENV     PHPVERSION=7.4
RUN     apt-get install -y --no-install-recommends \
                php${PHPVERSION} \
                php${PHPVERSION}-fpm \
                php${PHPVERSION}-apcu \
                php${PHPVERSION}-bcmath \
                php${PHPVERSION}-cli \
                php${PHPVERSION}-curl \
                php${PHPVERSION}-dom \
                php${PHPVERSION}-gd \
                php${PHPVERSION}-igbinary \
                php${PHPVERSION}-imagick \
                php${PHPVERSION}-json \
                php${PHPVERSION}-memcached \
                php${PHPVERSION}-mbstring \
#               php${PHPVERSION}-mcrypt \
                php${PHPVERSION}-mysql \
                php${PHPVERSION}-opcache \
                php${PHPVERSION}-pgsql \
                php${PHPVERSION}-readline \
#               php${PHPVERSION}-recode \
                php${PHPVERSION}-redis \
                php${PHPVERSION}-soap \
                php${PHPVERSION}-tidy \
                php${PHPVERSION}-xml \
                php${PHPVERSION}-zip \
        && apt-get -y autoremove && apt-get -y autoclean

ENV     PHPVERSION=8.0
RUN     apt-get install -y --no-install-recommends \
                php${PHPVERSION} \
                php${PHPVERSION}-fpm \
                php${PHPVERSION}-apcu \
                php${PHPVERSION}-bcmath \
                php${PHPVERSION}-cli \
                php${PHPVERSION}-curl \
                php${PHPVERSION}-dom \
                php${PHPVERSION}-gd \
                php${PHPVERSION}-igbinary \
                php${PHPVERSION}-imagick \
#                php${PHPVERSION}-json \
                php${PHPVERSION}-memcached \
                php${PHPVERSION}-mbstring \
#               php${PHPVERSION}-mcrypt \
                php${PHPVERSION}-mysql \
                php${PHPVERSION}-opcache \
                php${PHPVERSION}-pgsql \
                php${PHPVERSION}-readline \
#               php${PHPVERSION}-recode \
                php${PHPVERSION}-redis \
                php${PHPVERSION}-soap \
                php${PHPVERSION}-tidy \
                php${PHPVERSION}-xml \
                php${PHPVERSION}-zip \
        && apt-get -y autoremove && apt-get -y autoclean

RUN	mv /etc/apache2 /etc/apache2.orig && mkdir -p /etc/apache2 \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer \
        && apt-get -y autoremove && apt-get -y autoclean \
        && rm -rf /var/lib/apt/lists/*

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

