# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/apache-phpfpm for a recent one

FROM    eilandert/php-fpm:deb-multi
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV     LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

COPY    bootstrap.sh /bootstrap.sh
COPY	conf-available /tmp/conf-available

RUN set -ex ;\
    chmod +x /bootstrap.sh ;\
    apt-get -y update ;\
    apt-get install -y --no-install-recommends apache2 apache2-utils ;\
    a2dismod status mpm_prefork ;\
    a2enmod mpm_event proxy_fcgi setenvif rewrite expires headers remoteip ;\
    cp /tmp/conf-available/php${PHPVERSION}-fpm.conf /etc/apache2/conf-available ;\
    mv /etc/apache2 /etc/apache2.orig && mkdir -p /etc/apache2 ;\
#    mv /etc/php /etc/php.orig && mkdir -p /etc/php ;\
    mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer ;\
    apt-get -y autoremove && apt-get -y clean && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/* ;\
    echo "background_thread:true,metadata_thp:auto" > /etc/malloc.conf

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

