FROM    eilandert/ubuntu-base:latest
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV	PHPVERSION=7.2
ENV	MODE=multi
ENV	TZ=Europe/Amsterdam

COPY    bootstrap.sh /bootstrap.sh

RUN     apt-get install -y --no-install-recommends software-properties-common \
	&& add-apt-repository -y ppa:ondrej/apache2 && add-apt-repository -y ppa:ondrej/php \
        && apt-get -y update && apt-get -y upgrade \
        && apt-get install -y nullmailer mailutils \
	&& apt-get install -y --no-install-recommends \
                apache2 \
                apache2-utils \
                php5.6 \
                php5.6-fpm \
                php5.6-bcmath \
                php5.6-cli \
                php5.6-curl \
                php5.6-dom \
                php5.6-gd \
                php5.6-igbinary \
                php5.6-json \
                php5.6-mbstring \
		php5.6-mcrypt \
                php5.6-mysql \
                php5.6-opcache \
                php5.6-readline \
		php5.6-recode \
                php5.6-redis \
                php5.6-soap \
                php5.6-tidy \
                php5.6-xml \
                php5.6-zip \
                php-apcu \
                php-imagick \
                php-pgsql \
                php7.2 \
                php7.2-fpm \
                php7.2-bcmath \
                php7.2-cli \
                php7.2-curl \
                php7.2-dom \
                php7.2-gd \
                php7.2-igbinary \
                php7.2-json \
                php7.2-mbstring \
                php7.2-mysql \
                php7.2-opcache \
                php7.2-readline \
                php7.2-recode \
                php7.2-redis \
                php7.2-soap \
                php7.2-tidy \
                php7.2-xml \
                php7.2-zip \
                php7.4 \
                php7.4-fpm \
                php7.4-bcmath \
                php7.4-cli \
                php7.4-curl \
                php7.4-dom \
                php7.4-gd \
                php7.4-igbinary \
                php7.4-json \
                php7.4-mbstring \
                php7.4-mysql \
                php7.4-opcache \
                php7.4-readline \
                php7.2-recode \
                php7.4-redis \
                php7.4-soap \
                php7.4-tidy \
                php7.4-xml \
                php7.4-zip \
                php8.0 \
                php8.0-fpm \
                php8.0-bcmath \
                php8.0-cli \
                php8.0-curl \
                php8.0-dom \
                php8.0-gd \
                php8.0-igbinary \
                php8.0-mbstring \
                php8.0-mysql \
                php8.0-opcache \
                php8.0-readline \
                php8.0-redis \
                php8.0-soap \
                php8.0-tidy \
                php8.0-xml \
                php8.0-zip \
	&& apt-get -y purge software-properties-common unattended-upgrades apt-utils \
        && apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* \
        && chmod +x /bootstrap.sh \
	&& a2enmod proxy_fcgi setenvif rewrite expires headers remoteip \
#	&& a2enconf php7.4 \
	&& a2dismod status \
        && mv /etc/apache2 /etc/apache2.orig && mkdir -p /etc/apache2 \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

