FROM    eilandert/ubuntu-base:latest
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV	PHPVERSION=7.2

COPY    bootstrap.sh /bootstrap.sh

RUN     add-apt-repository -y ppa:ondrej/apache2 && add-apt-repository -y ppa:ondrej/php \
        && apt-get -y update && apt-get -y upgrade \
        && apt install -y nullmailer mailutils \
	&& apt install -y --no-install-recommends \
                apache2 \
                apache2-utils \
                php7.2 \
                php7.2-fpm \
                php7.2-bcmath \
                php7.2-cli \
                php7.2-curl \
                php7.2-dom \
                php7.2-gd \
                php7.2-igbinary \
                php7.2-json \
                php7.2-mbstring \
                php7.2-mysql \
                php7.2-opcache \
                php7.2-readline \
                php7.2-redis \
                php7.2-soap \
                php7.2-tidy \
                php7.2-xml \
                php7.2-zip \
                php-apcu \
                php-imagick \
                php-pgsql \
	&& apt-get -y purge software-properties-common unattended-upgrades apt-utils \
        && apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* \
        && rm -rf /etc/php/5.6 /etc/php/7.0 /etc/php/7.1 /etc/php/7.3 /etc/php/7.2 /etc/php8.0 \
	&& cd /usr/lib/php && rm -rf 20131226 20151012 20160303 20180731 20190902 20200930\
        && chmod +x /bootstrap.sh \
	&& a2enmod proxy_fcgi setenvif rewrite expires headers remoteip \
	&& a2enconf php7.2-fpm \
	&& a2dismod status \
        && mv /etc/apache2 /etc/apache2.orig && mkdir -p /etc/apache2 \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

