# syntax=docker/dockerfile:1.7
FROM alpine:edge

LABEL   org.opencontainers.image.authors="eilandert" \
        org.opencontainers.image.source="https://github.com/eilandert/dockerized" \
        maintainer="Thijs Eilander <eilander@myguard.nl>"

COPY --chmod=0755 bootstrap.sh /bootstrap.sh
COPY syslog-ng.conf /etc/syslog-ng

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    set -eux ;\
    apk update && apk upgrade ;\
    apk add --no-cache dovecot dovecot-lmtpd dovecot-sql dovecot dovecot-pigeonhole-plugin dovecot-pop3d rspamd-client ca-certificates tzdata openssl rsyslog ;\
    rm -rf /usr/src/* ;\
    mv /etc/dovecot /etc/dovecot.orig ;\
    echo "5.9.124.53 public.pyzor.org" >> /etc/hosts ;\
    addgroup -S -g 5000 vmail && adduser -S -G vmail -u 5000 vmail

EXPOSE 24 143 110 993 995 4190

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 CMD pgrep -x dovecot > /dev/null && doveadm who -1 > /dev/null 2>&1 || exit 1

CMD ["/bootstrap.sh"]
