# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/php-fpm for a recent one
FROM    eilandert/debian-base:stable
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>" \
        org.opencontainers.image.title="PHP-FPM" \
        org.opencontainers.image.description="PHP-FPM FastCGI Process Manager" \
        org.opencontainers.image.url="https://github.com/eilandert/dockerized" \
        org.opencontainers.image.source="https://github.com/eilandert/dockerized/tree/master/php-fpm" \
        org.opencontainers.image.vendor="MyGuard" \
        org.opencontainers.image.version="#VERSION#"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV    PHPVERSION=8.2
ENV    MODE=FPM

COPY    bootstrap.sh /bootstrap.sh

RUN set -ex ;\
    echo "deb [trusted=yes] http://edge.deb.myguard.nl:8888/mirror/ondrej-php ${DIST} main"  > /etc/apt/sources.list.d/ondrej-ppa.list ;\
    apt-get -y update ;\
    apt-get install -y nullmailer mailutils ;\
    rm -rf /var/spool/nullmailer/trigger ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -xe ;\
    apt-get update ;\
    apt-get install -y --no-install-recommends \
      php8.2 \
      php8.2-fpm \
      php8.2-apcu \
      php8.2-bcmath \
      php8.2-cli \
      php8.2-curl \
      php8.2-dom \
      php8.2-exif \
      php8.2-gd \
      php8.2-gmp \
      php8.2-igbinary \
      php8.2-imagick \
      php8.2-imap \
      php8.2-intl \
      #removedinphp80#php8.2-json \
      php8.2-ldap \
      #removedinphp72#php8.2-mcrypt \
      php8.2-memcache \
      php8.2-memcached \
      php8.2-mbstring \
      php8.2-mysql \
      php8.2-opcache \
      php8.2-pspell \
      php8.2-pgsql \
      php8.2-readline \
      #removedinphp74#php8.2-recode \
      php8.2-redis \
      php8.2-soap \
      php8.2-sqlite3 \
      php8.2-tidy \
      php8.2-xml \
      php8.2-zstd \
      php8.2-snuffleupagus \
      php8.2-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -ex ;\
    cd /tmp ;\
    /usr/bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" ;\
    cat /tmp/composer-setup.php | /usr/bin/php -- --filename=composer --install-dir=/usr/bin ;\
    /usr/bin/php -r "unlink('composer-setup.php');" ;\
    /usr/bin/php -r "copy('https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar', '/usr/bin/wp');" ;\
    chmod +x /usr/bin/wp

RUN rm -rf /var/lib/apt/lists/* /tmp/* ;\
    rm -rf /etc/php/5.6 /usr/lib/php/20131226 ;\
    rm -rf /etc/php/7.0 /usr/lib/php/20151012 ;\
    rm -rf /etc/php/7.1 /usr/lib/php/20160303 ;\
    rm -rf /etc/php/7.2 /usr/lib/php/20170718 ;\
    rm -rf /etc/php/7.3 /usr/lib/php/20180731 ;\
    rm -rf /etc/php/7.4 /usr/lib/php/20190902 ;\
    rm -rf /etc/php/8.0 /usr/lib/php/20200930 ;\
    rm -rf /etc/php/8.1 /usr/lib/php/20210902 ;\
    #rm -rf /etc/php/8.2 /usr/lib/php/20220829 ;\
    rm -rf /etc/php/8.3 /usr/lib/php/20230831 ;\
    rm -rf /etc/php/8.4 /usr/lib/php/20240924 ;\
    rm -rf /etc/php/8.5 /usr/lib/php/20250925 ;\
    mv /etc/php /etc/php.orig && mkdir -p /etc/php ;\
    mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer ;\
    chmod 755 /bootstrap.sh
EXPOSE  9000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD php-fpm -r 2>/dev/null || exit 1

CMD     ["/bootstrap.sh"]

