# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/php-fpm for a recent one
FROM    eilandert/debian-base:stable
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV	PHPVERSION=MULTI
ENV	MODE=MULTI

COPY    bootstrap.sh /bootstrap.sh

RUN set -ex ;\
    echo "deb [trusted=yes] http://edge.deb.myguard.nl:8888/mirror/ondrej-php ${DIST} main"  > /etc/apt/sources.list.d/ondrej-ppa.list ;\
    apt-get -y update ;\
    apt-get install -y nullmailer mailutils ;\
    rm -rf /var/spool/nullmailer/trigger ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php5.6 \
      php5.6-fpm \
      php5.6-apcu \
      php5.6-bcmath \
      php5.6-cli \
      php5.6-curl \
      php5.6-dom \
      php5.6-exif \
      php5.6-gd \
      php5.6-gmp \
      php5.6-igbinary \
      php5.6-imagick \
      php5.6-imap \
      php5.6-intl \
      php5.6-json \
      php5.6-ldap \
      php5.6-mcrypt \
      php5.6-memcache \
      php5.6-mbstring \
      php5.6-mysql \
      php5.6-opcache \
      php5.6-pspell \
      php5.6-pgsql \
      php5.6-readline \
      php5.6-recode \
      php5.6-redis \
      php5.6-soap \
      php5.6-sqlite3 \
      php5.6-tidy \
      php5.6-xml \
      php5.6-zstd \
      php5.6-snuffleupagus ;\
      php5.6-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php7.2 \
      php7.2-fpm \
      php7.2-apcu \
      php7.2-bcmath \
      php7.2-cli \
      php7.2-curl \
      php7.2-dom \
      php7.2-exif \
      php7.2-gd \
      php7.2-gmp \
      php7.2-igbinary \
      php7.2-imagick \
      php7.2-imap \
      php7.2-intl \
      php7.2-json \
      php7.2-ldap \
      php7.2-memcache \
      php7.2-mbstring \
      php7.2-mysql \
      php7.2-opcache \
      php7.2-pspell \
      php7.2-pgsql \
      php7.2-readline \
      php7.2-recode \
      php7.2-redis \
      php7.2-soap \
      php7.2-sqlite3 \
      php7.2-tidy \
      php7.2-xml \
      php7.2-zstd \
      php7.2-snuffleupagus ;\
      php7.2-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php7.4 \
      php7.4-fpm \
      php7.4-apcu \
      php7.4-bcmath \
      php7.4-cli \
      php7.4-curl \
      php7.4-dom \
      php7.4-exif \
      php7.4-gd \
      php7.4-gmp \
      php7.4-igbinary \
      php7.4-imagick \
      php7.4-imap \
      php7.4-intl \
      php7.4-json \
      php7.4-ldap \
      php7.4-memcache \
      php7.4-mbstring \
      php7.4-mysql \
      php7.4-opcache \
      php7.4-pspell \
      php7.4-pgsql \
      php7.4-readline \
      php7.4-redis \
      php7.4-soap \
      php7.4-sqlite3 \
      php7.4-tidy \
      php7.4-xml \
      php7.4-zstd \
      php7.4-snuffleupagus ;\
      php7.4-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php8.0 \
      php8.0-fpm \
      php8.0-apcu \
      php8.0-bcmath \
      php8.0-cli \
      php8.0-curl \
      php8.0-dom \
      php8.0-exif \
      php8.0-gd \
      php8.0-gmp \
      php8.0-igbinary \
      php8.0-imagick \
      php8.0-imap \
      php8.0-intl \
      php8.0-ldap \
      php8.0-memcache \
      php8.0-mbstring \
      php8.0-mysql \
      php8.0-opcache \
      php8.0-pspell \
      php8.0-pgsql \
      php8.0-readline \
      php8.0-redis \
      php8.0-soap \
      php8.0-sqlite3 \
      php8.0-tidy \
      php8.0-xml \
      php8.0-zstd \
      php8.0-snuffleupagus ;\
      php8.0-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php8.1 \
      php8.1-fpm \
      php8.1-apcu \
      php8.1-bcmath \
      php8.1-cli \
      php8.1-curl \
      php8.1-dom \
      php8.1-exif \
      php8.1-gd \
      php8.1-gmp \
      php8.1-igbinary \
      php8.1-imagick \
      php8.1-imap \
      php8.1-intl \
      php8.1-ldap \
      php8.1-memcache \
      php8.1-mbstring \
      php8.1-mysql \
      php8.1-opcache \
      php8.1-pspell \
      php8.1-pgsql \
      php8.1-readline \
      php8.1-redis \
      php8.1-soap \
      php8.1-sqlite3 \
      php8.1-tidy \
      php8.1-xml \
      php8.1-zstd \
      php8.1-snuffleupagus ;\
      php8.1-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php8.2 \
      php8.2-fpm \
      php8.2-apcu \
      php8.2-bcmath \
      php8.2-cli \
      php8.2-curl \
      php8.2-dom \
      php8.2-exif \
      php8.2-gd \
      php8.2-gmp \
      php8.2-igbinary \
      php8.2-imagick \
      php8.2-imap \
      php8.2-intl \
      php8.2-ldap \
      php8.2-memcache \
      php8.2-mbstring \
      php8.2-mysql \
      php8.2-opcache \
      php8.2-pspell \
      php8.2-pgsql \
      php8.2-readline \
      php8.2-redis \
      php8.2-soap \
      php8.2-sqlite3 \
      php8.2-tidy \
      php8.2-xml \
      php8.2-zstd \
      php8.2-snuffleupagus ;\
      php8.2-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php8.3 \
      php8.3-fpm \
      php8.3-apcu \
      php8.3-bcmath \
      php8.3-cli \
      php8.3-curl \
      php8.3-dom \
      php8.3-exif \
      php8.3-gd \
      php8.3-gmp \
      php8.3-igbinary \
      php8.3-imagick \
      php8.3-imap \
      php8.3-intl \
      php8.3-ldap \
      php8.3-memcache \
      php8.3-mbstring \
      php8.3-mysql \
      php8.3-opcache \
      php8.3-pspell \
      php8.3-pgsql \
      php8.3-readline \
      php8.3-redis \
      php8.3-soap \
      php8.3-sqlite3 \
      php8.3-tidy \
      php8.3-xml \
      php8.3-zstd \
      php8.3-snuffleupagus ;\
      php8.3-zip ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -ex ;\
    cd /tmp ;\
    /usr/bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" ;\
    cat /tmp/composer-setup.php | /usr/bin/php -- --filename=composer --install-dir=/usr/bin ;\
    /usr/bin/php -r "unlink('composer-setup.php');" ;\
    /usr/bin/php -r "copy('https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar', '/usr/bin/wp');" ;\
    chmod +x /usr/bin/wp 

RUN rm -rf /var/lib/apt/lists/* /tmp/* ;\
    #rm -rf /etc/php/5.6 /usr/lib/php/20131226 ;\
    #rm -rf /etc/php/7.0 /usr/lib/php/20151012 ;\
    #rm -rf /etc/php/7.1 /usr/lib/php/20160303 ;\
    #rm -rf /etc/php/7.2 /usr/lib/php/20170718 ;\
    #rm -rf /etc/php/7.3 /usr/lib/php/20180731 ;\
    #rm -rf /etc/php/7.4 /usr/lib/php/20190902 ;\
    #rm -rf /etc/php/8.0 /usr/lib/php/20200930 ;\
    #rm -rf /etc/php/8.1 /usr/lib/php/20210902 ;\
    #rm -rf /etc/php/8.2 /usr/lib/php/20220829 ;\
    #rm -rf /etc/php/8.3 /usr/lib/php/20230831 ;\
    mv /etc/php /etc/php.orig && mkdir -p /etc/php ;\
    mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer ;\
    chmod 755 /bootstrap.sh

CMD     ["/bootstrap.sh"]

EXPOSE  9000
