# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/php-fpm for a recent one
FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV	PHPVERSION=5.6
ENV	MODE=FPM

COPY    bootstrap.sh /bootstrap.sh
ADD	https://getcomposer.org/installer /tmp/composer-setup.php

RUN set -ex ;\
#    . /etc/os-release ;\
#    echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/ondrej-php.list ;\
    apt-get -y update ;\
#    apt-get install -y libpcre2-8-0 libpcre3 ;\
    apt-get install -y nullmailer mailutils ;\
    rm -rf /var/spool/nullmailer/trigger ;\
    apt-get install -y --no-install-recommends \
      php5.6 \
      php5.6-fpm \
      php5.6-apcu \
      php5.6-bcmath \
      php5.6-cli \
      php5.6-curl \
      php5.6-dom \
      php5.6-exif \
      php5.6-gd \
      php5.6-gmp \
      php5.6-igbinary \
      php5.6-imagick \
      php5.6-imap \
      php5.6-intl \
      php5.6-json \
      php5.6-ldap \
      php5.6-mcrypt \
      php5.6-memcache \
      php5.6-memcached \
      php5.6-mbstring \
      php5.6-mysql \
      php5.6-opcache \
      php5.6-pspell \
      php5.6-pgsql \
      php5.6-readline \
      php5.6-recode \
      php5.6-redis \
      php5.6-soap \
      php5.6-sqlite \
      php5.6-tidy \
      php5.6-xml \
      php5.6-zip \
    ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    cat /tmp/composer-setup.php | php -- --filename=composer --install-dir=/usr/bin ;\
    rm -rf /var/lib/apt/lists/* /tmp/* ;\
    #rm -rf /etc/php/5.6 /usr/lib/php/20131226 ;\
    rm -rf /etc/php/7.0 /usr/lib/php/20151012 ;\
    rm -rf /etc/php/7.1 /usr/lib/php/20160303 ;\
    rm -rf /etc/php/7.2 /usr/lib/php/20170718 ;\
    rm -rf /etc/php/7.3 /usr/lib/php/20180731 ;\
    rm -rf /etc/php/7.4 /usr/lib/php/20190902 ;\
    rm -rf /etc/php/8.0 /usr/lib/php/20200930 ;\
    mv /etc/php /etc/php.orig && mkdir -p /etc/php ;\
    mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer ;\
    chmod 755 /bootstrap.sh

CMD     ["/bootstrap.sh"]

EXPOSE  9000
