# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/php-fpm for a recent one
FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV	PHPVERSION=8.2
ENV	MODE=FPM

COPY    bootstrap.sh /bootstrap.sh

RUN set -ex ;\
    echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu/ ${DIST} main" > /etc/apt/sources.list.d/ondrej-ppa.list ;\
    apt-get -y update ;\
    apt-get install -y nullmailer mailutils ;\
    rm -rf /var/spool/nullmailer/trigger ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -x ;\
    apt-get update ;\
    apt-get install -m -y --no-install-recommends \
      php8.2 \
      php8.2-fpm \
      php8.2-apcu \
      php8.2-bcmath \
      php8.2-cli \
      php8.2-curl \
      php8.2-dom \
      php8.2-exif \
      php8.2-gd \
      php8.2-gmp \
      php8.2-igbinary \
      php8.2-imagick \
      php8.2-imap \
      php8.2-intl \
      php8.2-ldap \
      php8.2-memcache \
      php8.2-memcached \
      php8.2-mbstring \
      php8.2-mysql \
      php8.2-opcache \
      php8.2-pspell \
      php8.2-pgsql \
      php8.2-readline \
      php8.2-redis \
      php8.2-soap \
      php8.2-sqlite3 \
      php8.2-tidy \
      php8.2-xml \
      php8.2-zip \
      php8.2-zstd ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/*

RUN set -ex ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    cd /tmp ;\
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" ;\
    cat /tmp/composer-setup.php | php -- --filename=composer --install-dir=/usr/bin ;\
    php -r "unlink('composer-setup.php');" ;\
    rm -rf /var/lib/apt/lists/* /tmp/* ;\
    rm -rf /etc/php/5.6 /usr/lib/php/20131226 ;\
    rm -rf /etc/php/7.0 /usr/lib/php/20151012 ;\
    rm -rf /etc/php/7.1 /usr/lib/php/20160303 ;\
    rm -rf /etc/php/7.2 /usr/lib/php/20170718 ;\
    rm -rf /etc/php/7.3 /usr/lib/php/20180731 ;\
    rm -rf /etc/php/7.4 /usr/lib/php/20190902 ;\
    rm -rf /etc/php/8.0 /usr/lib/php/20200930 ;\
    #rm -rf /etc/php/8.2 /usr/lib/php/20210902 ;\
    rm -rf /etc/php/8.2 /usr/lib/php/20220829 ;\
    mv /etc/php /etc/php.orig && mkdir -p /etc/php ;\
    mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer ;\
    chmod 755 /bootstrap.sh

CMD     ["/bootstrap.sh"]

EXPOSE  9000
