FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV	PHPVERSION=7.2
ENV     TZ=Europe/Amsterdam

COPY    bootstrap.sh /bootstrap.sh

RUN     echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu focal main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-focal.list \
        && apt-get -y update && apt-get -y upgrade \
        && apt-get install -y nullmailer mailutils \
        && apt-get install -y --no-install-recommends \
                php7.2 \
                php7.2-fpm \
                php7.2-bcmath \
                php7.2-cli \
                php7.2-curl \
                php7.2-dom \
                php7.2-gd \
                php7.2-igbinary \
                php7.2-json \
                php7.2-memcached \
                php7.2-mbstring \
                php7.2-mysql \
                php7.2-opcache \
                php7.2-readline \
		php7.2-recode \
                php7.2-redis \
                php7.2-soap \
                php7.2-tidy \
                php7.2-xml \
                php7.2-zip \
                php-apcu \
                php-imagick \
                php-pgsql \
        && apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* \
        && rm -rf /etc/php/5.6 /etc/php/7.0 /etc/php/7.1 /etc/php/7.3 /etc/php/7.2 /etc/php8.0 \
	&& cd /usr/lib/php && rm -rf 20131226 20151012 20160303 20180731 20190902 20200930\
        && chmod +x /bootstrap.sh \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer

CMD     ["/bootstrap.sh"]

EXPOSE  9000 9000

