FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV	PHPVERSION=5.6
ENV	TZ=Europe/Amsterdam

COPY    bootstrap.sh /bootstrap.sh

RUN     UBUNTU=`lsb_release -c -s` \
        && echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU} main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-${UBUNTU}.list \
        && apt-get -y update && apt-get -y upgrade \
        && apt-get install -y nullmailer mailutils \
	&& apt-get install -y --no-install-recommends \
                php5.6 \
                php5.6-fpm \
                php5.6-bcmath \
                php5.6-cli \
                php5.6-curl \
                php5.6-dom \
                php5.6-gd \
                php5.6-igbinary \
                php5.6-json \
		php5.6-memcached \
                php5.6-mbstring \
		php5.6-mcrypt \
                php5.6-mysql \
                php5.6-opcache \
                php5.6-readline \
		php5.6-recode \
                php5.6-redis \
                php5.6-soap \
                php5.6-tidy \
                php5.6-xml \
                php5.6-zip \
                php-apcu \
                php-imagick \
                php-pgsql \
        && apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* \
        && rm -rf /etc/php/7.0 /etc/php/7.1 /etc/php/7.2 /etc/php/7.3 /etc/php/7.4 /etc/php8.0 \
	&& cd /usr/lib/php && rm -rf 20151012 20160303 20170718 20180731 20190902 20200930 \
        && chmod +x /bootstrap.sh \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer

CMD     ["/bootstrap.sh"]

EXPOSE  9000:9000

