FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV	PHPVERSION=8.0
ENV	MODE=FPM

COPY    bootstrap.sh /bootstrap.sh
ADD	https://getcomposer.org/installer /tmp/composer-setup.php

RUN set -ex ;\
    . /etc/os-release ;\
    echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-${UBUNTU_CODENAME}.list ;\
    apt-get -y update ;\
    apt-get install -y libpcre2-8-0 libpcre3 ;\
    apt-get install -y nullmailer mailutils ;\
    rm -rf /var/spool/nullmailer/trigger ;\
    apt-get install -y --no-install-recommends \
      php8.0 \
      php8.0-fpm \
      php8.0-apcu \
      php8.0-bcmath \
      php8.0-cli \
      php8.0-curl \
      php8.0-dom \
      php8.0-exif \
      php8.0-gd \
      php8.0-igbinary \
      php8.0-imagick \
      php8.0-imap \
      php8.0-intl \
      php8.0-ldap \
      php8.0-memcache \
      php8.0-memcached \
      php8.0-mbstring \
      php8.0-mysql \
      php8.0-opcache \
      php8.0-pspell \
      php8.0-pgsql \
      php8.0-readline \
      php8.0-redis \
      php8.0-soap \
      php8.0-sqlite \
      php8.0-tidy \
      php8.0-xml \
      php8.0-zip \
    ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    cat /tmp/composer-setup.php | php -- --filename=composer --install-dir=/usr/bin ;\
    rm -rf /var/lib/apt/lists/* ;\
    rm -rf /etc/php/5.6 /usr/lib/php/20131226 ;\
    rm -rf /etc/php/7.0 /usr/lib/php/20151012 ;\
    rm -rf /etc/php/7.1 /usr/lib/php/20160303 ;\
    rm -rf /etc/php/7.2 /usr/lib/php/20170718 ;\
    rm -rf /etc/php/7.3 /usr/lib/php/20180731 ;\
    rm -rf /etc/php/7.4 /usr/lib/php/20190902 ;\
    #rm -rf /etc/php/8.0 /usr/lib/php/20200930 ;\
    mv /etc/php /etc/php.orig && mkdir -p /etc/php ;\
    mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer ;\
    chmod 755 /bootstrap.sh

CMD     ["/bootstrap.sh"]

EXPOSE  9000

