FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam

COPY    bootstrap.sh /bootstrap.sh

RUN     . /etc/os-release \
        && echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-${UBUNTU_CODENAME}.list \
        && apt-get -y update \
        && apt-get install -y nullmailer mailutils \
        && apt-get -y autoremove && apt-get -y autoclean \
        chmod +x /bootstrap.sh

RUN     apt-get update \
	&& apt-get install -y --no-install-recommends \
                php7.2 \
                php7.2-fpm \
                php7.2-apcu \
                php7.2-bcmath \
                php7.2-cli \
                php7.2-curl \
                php7.2-dom \
                php7.2-gd \
                php7.2-igbinary \
                php7.2-imagick \
                php7.2-memcached \
                php7.2-mbstring \
                php7.2-mysql \
                php7.2-opcache \
                php7.2-pgsql \
                php7.2-readline \
                php7.2-redis \
                php7.2-soap \
                php7.2-tidy \
                php7.2-xml \
                php7.2-zip \
        && apt-get -y autoremove && apt-get -y autoclean \
        && rm -rf /var/lib/apt/lists/*


RUN     apt-get -y update && apt-get -y upgrade \
	&& apt-get -y autoremove && apt-get -y autoclean \
        && rm -rf /var/lib/apt/lists/* \
	&& rm -rf /etc/php/5.6 /usr/lib/php/20131226 \
        && rm -rf /etc/php/7.0 /usr/lib/php/20151012 \
        && rm -rf /etc/php/7.1 /usr/lib/php/20160303 \
        #&& rm -rf /etc/php/7.2 /usr/lib/php/20170718 \
        && rm -rf /etc/php/7.3 /usr/lib/php/20180731 \
        && rm -rf /etc/php/7.4 /usr/lib/php/20190902 \
        && rm -rf /etc/php/8.0 /usr/lib/php/20200930 \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer 

CMD     ["/bootstrap.sh"]

EXPOSE  9000

