	php#PHPVERSION# \
        php#PHPVERSION#-fpm \
        php#PHPVERSION#-apcu \
        php#PHPVERSION#-bcmath \
        php#PHPVERSION#-cli \
        php#PHPVERSION#-curl \
        php#PHPVERSION#-dom \
        php#PHPVERSION#-gd \
        php#PHPVERSION#-igbinary \
        php#PHPVERSION#-imagick \
        #removedinphp80#php#PHPVERSION#-json \
	#removedinphp72#php#PHPVERSION#-mcrypt \
	php#PHPVERSION#-memcache \
        php#PHPVERSION#-memcached \
        php#PHPVERSION#-mbstring \
        php#PHPVERSION#-mysql \
        php#PHPVERSION#-opcache \
        php#PHPVERSION#-pspell \
        php#PHPVERSION#-pgsql \
        php#PHPVERSION#-readline \
        #removedinphp74#php#PHPVERSION#-recode \
        php#PHPVERSION#-redis \
        php#PHPVERSION#-soap \
        php#PHPVERSION#-tidy \
        php#PHPVERSION#-xml \
        php#PHPVERSION#-zip \
