FROM    eilandert/ubuntu-base:rolling
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     TZ=Europe/Amsterdam
ENV	PHPVERSION=7.4
ENV	MODE=FPM

COPY    bootstrap.sh /bootstrap.sh
ADD	https://getcomposer.org/installer /tmp/composer-setup.php

RUN     . /etc/os-release \
        && echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-${UBUNTU_CODENAME}.list \
        && apt-get -y update \
        && apt-get install -y nullmailer mailutils \
        && apt-get install -y --no-install-recommends \
	php7.4 \
        php7.4-fpm \
        php7.4-apcu \
        php7.4-bcmath \
        php7.4-cli \
        php7.4-curl \
        php7.4-dom \
        php7.4-gd \
        php7.4-igbinary \
        php7.4-imagick \
        php7.4-json \
        php7.4-memcached \
        php7.4-mbstring \
        php7.4-mysql \
        php7.4-opcache \
        php7.4-pgsql \
        php7.4-readline \
        php7.4-redis \
        php7.4-soap \
        php7.4-tidy \
        php7.4-xml \
        php7.4-zip \
	&& apt-get -y autoremove && apt-get -y autoclean \
        && rm -rf /var/lib/apt/lists/* \
        && rm -rf /etc/php/5.6 /usr/lib/php/20131226 \
        && rm -rf /etc/php/7.0 /usr/lib/php/20151012 \
        && rm -rf /etc/php/7.1 /usr/lib/php/20160303 \
        && rm -rf /etc/php/7.2 /usr/lib/php/20170718 \
        && rm -rf /etc/php/7.3 /usr/lib/php/20180731 \
        #&& rm -rf /etc/php/7.4 /usr/lib/php/20190902 \
        && rm -rf /etc/php/8.0 /usr/lib/php/20200930 \
        && mv /etc/php /etc/php.orig && mkdir -p /etc/php \
        && mv /etc/nullmailer /etc/nullmailer.orig && mkdir -p /etc/nullmailer \
        && chmod 755 /bootstrap.sh

CMD     ["/bootstrap.sh"]

EXPOSE  9000

