# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/roundcube for a recent one

FROM    eilandert/apache-phpfpm:deb-7.4
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     INSTALLDIR="/var/www/html"

# fetch the last version, generated in the docker build script
COPY     .lastversion /tmp/lastversion

COPY	bootstrap.sh /

RUN set -x ;\
    LASTVERSION=$(cat /tmp/lastversion) ;\
    apt-get -y update ;\
    rm -rf /etc/php && mv /etc/php.orig /etc/php ;\
    apt-get install -y --no-install-recommends \
      git \
      unzip \
      curl \
      locales ;\
    rm -rf ${INSTALLDIR} ;\
    mkdir ${INSTALLDIR} ;\
    curl -fSL https://github.com/roundcube/roundcubemail/releases/download/${LASTVERSION}/roundcubemail-${LASTVERSION}-complete.tar.gz | \
      tar xz --strip-components=1 -C ${INSTALLDIR} ;\
    cd ${INSTALLDIR} ;\
    mv composer.json-dist composer.json ;\
    composer config -g secure-http false ;\
    composer -n update --no-dev;\
#    bin/install-jsdeps.sh ;\
    composer -n require mobiledetect/mobiledetectlib ;\
    composer -n require roundcube/elastic4mobile dev-master ;\
    #2fa
    composer -n require kolab/kolab_2fa ;\
    composer require "endroid/qrcode" "~1.5.0" --no-update ;\
    composer require "spomky-labs/otphp" "~5.0.0" --no-update ;\
    composer require "enygma/yubikey" "~3.2" ;\
    cd ${INSTALLDIR} ;\
   #show_folder_size
   mkdir -p plugins/show_folder_size ;\
   curl -L https://github.com/jfcherng-roundcube/plugin-show-folder-size/archive/master.tar.gz | \
     tar xz --strip-components=1 -C plugins/show_folder_size ;\
   #quota
   mkdir -p plugins/quota ;\
   curl -L https://github.com/jfcherng-roundcube/plugin-quota/archive/master.tar.gz | \
     tar xz --strip-components=1 -C plugins/quota ;\
   #account_details
    mkdir -p plugins/account_details ;\
    curl -L https://github.com/texxasrulez/account_details/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/account_details ;\ 
   #responses
    mkdir -p plugins/responses ;\
    curl -L https://github.com/random-cuber/responses/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/responses ;\
    #fail2ban
    mkdir -p plugins/fail2ban ;\
    curl -L https://github.com/texxasrulez/roundcube_fail2ban/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/fail2ban ;\
    #RCGuard
    mkdir -p plugins/rcguard ;\
    curl -L https://github.com/dsoares/roundcube-rcguard/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/rcguard ;\
    #swipe
    mkdir -p plugins/swipe ;\
    curl -L https://github.com/johndoh/roundcube-swipe/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/swipe ;\
    #advanced_search
    mkdir -p plugins/advanced_search ;\
    curl -L https://github.com/texxasrulez/advanced_search/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/advanced_search ;\
    #persistent_login
    mkdir -p plugins/persistent_login ;\
    curl -L https://github.com/texxasrulez/persistent_login/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/persistent_login ;\
    # Context Menu
    mkdir -p plugins/contextmenu ;\
    curl -L https://github.com/johndoh/roundcube-contextmenu/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/contextmenu ;\
    # Context Menu Folder
    mkdir -p plugins/contextmenu_folder ;\
    curl -L https://github.com/random-cuber/contextmenu_folder/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/contextmenu_folder ;\
    # Message Highlight
    mkdir -p plugins/message_highlight ;\
    curl -L https://github.com/texxasrulez/message_highlight/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/message_highlight ;\
    #Infinite Scroll
    mkdir -p plugins/infinitescroll ;\
    curl -L https://github.com/messagerie-melanie2/Roundcube-Plugin-Infinite-Scroll/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/infinitescroll ;\
    # Thunderbird Labels
    mkdir -p plugins/thunderbird_labels ;\
    curl -L https://github.com/mike-kfed/rcmail-thunderbird-labels/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/thunderbird_labels ;\
    # Remove Attach Position
    mkdir -p plugins/attachment_position ;\
    curl -L https://github.com/filhocf/roundcube-attachment_position/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/attachment_position ;\
    # HTML5 Notifier
    mkdir -p plugins/html5_notifier ;\
    curl -L https://github.com/filhocf/roundcube-html5_notifier/archive/master.tar.gz | \
      tar xz --strip-components=1 -C plugins/html5_notifier ;\
    # Mabola theme
    mkdir -p skins/mabola ;\
    curl -L https://github.com/filhocf/mabola/archive/master.tar.gz | \
      tar xz --strip-components=1 -C skins/mabola ;\
    # Mabola theme
    mkdir -p skins/mabola-blue ;\
    curl -L https://github.com/EstudioNexos/mabola-blue/archive/master.tar.gz | \
      tar xz --strip-components=1 -C skins/mabola-blue ;\
    # Chameleon theme
    mkdir -p skins/chameleon ;\
    curl -L https://github.com/filhocf/roundcube-chameleon/archive/master.tar.gz | \
      tar xz --strip-components=1 -C skins/chameleon ;\
    # Chameleon Blue theme
    mkdir -p skins/chameleon-blue ;\
    curl -L https://github.com/filhocf/roundcube-chameleon-blue/archive/master.tar.gz | \
      tar xz --strip-components=1 -C skins/chameleon-blue ;\
    for dir in `ls plugins`; do if [ -d plugins/$dir ]; then if [ -f plugins/$dir/composer.json ]; then echo $dir; composer upgrade plugins/$dir --no-dev; fi; fi; done ;\
    composer clear-cache ;\
    echo "include=/var/roundcube/config/phpfpm.conf" >> /etc/php/${PHPVERSION}/fpm/pool.d/www.conf ;\
    echo "include=/var/roundcube/config/phpfpm.conf.override" >> /etc/php/${PHPVERSION}/fpm/pool.d/www.conf ;\
    echo "Include /var/roundcube/config/httpd.conf" > /etc/apache2.orig/sites-enabled/000-default.conf ;\
    mv /etc/php /etc/php.orig && mkdir /etc/php ;\
    mkdir -p /var/roundcube/config.orig ;\
    cp ${INSTALLDIR}/config/defaults.inc.php /var/roundcube/config.orig ;\
    touch /var/roundcube/config.orig/phpfpm.conf.override ;\
    cp -rp ${INSTALLDIR}/plugins ${INSTALLDIR}/plugins.orig ;\
    apt-get -y purge git mailutils nullmailer curl ;\
    apt-get -y autoremove && apt-get -y clean && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/* /tmp/* ;\
    cd ${INSTALLDIR} ;\
    rm -rf ${INSTALLDIR}/installer ${INSTALLDIR}/.ci ${INSTALLDIR}/.tx ${INSTALLDIR}/.git* ${INSTALLDIR}/.travis.yml /root/.c* ;\
    rm -rf README.md INSTALL UPGRADING, LICENSE, CHANGELOG tests ${INSTALLDIR}/plugins/*/.git* ;\
#    rm -rf composer.json composer.lock jsdeps.json bin/install-jsdeps.sh *.orig vendor/pear/*/tests vendor/*/*/.git* vendor/pear/crypt_gpg/tools vendor/pear/console_commandline/docs vendor/pear/mail_mime/scripts vendor/pear/net_ldap2/doc vendor/pear/net_smtp/docs vendor/pear/net_smtp/examples vendor/pear/net_smtp/README.rst vendor/endroid/qrcode/tests temp/js_cache ;\
    rm -f /etc/apache2.orig/conf-enabled/other-vhosts-access-log.conf ;\
    rm -f ${INSTALLDIR}/index.html ;\
    chown -R www-data:www-data ${INSTALLDIR}/logs ;\
    chown -R www-data:www-data ${INSTALLDIR}/temp ;\
    chmod +x /bootstrap.sh

COPY httpd.conf /var/roundcube/config.orig
COPY phpfpm.conf /var/roundcube/config.orig

WORKDIR ${INSTALLDIR}
ENTRYPOINT ["/bootstrap.sh"]

VOLUME /var/roundcube/config
VOLUME /var/roundcube/db

