#!/bin/bash
# Main Dockerfile generation orchestrator
# This script coordinates generation of all Dockerfiles from templates
# Each component has its own .generate.sh script in its directory

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_section() {
    echo ""
    echo "===== $* ====="
}

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPTDIR"

# Ensure generate-lib.sh exists
if [[ ! -f generate-lib.sh ]]; then
    log_error "generate-lib.sh not found"
    exit 1
fi

log_section "Dockerfile Generation"

# Define components in dependency order
declare -a COMPONENTS=(
    "base"              # Layer 1: Base images
    "php-fpm"           # Layer 2: PHP-FPM (depends on base)
    "apache-phpfpm"     # Layer 2: Apache PHP-FPM (depends on base)
    "nginx"             # Layer 3: Nginx (depends on php-fpm)
    "angie"             # Layer 3: Angie (depends on nginx)
)

FAILED=0
FAILED_COMPONENTS=()

# Run each component's generation
for component in "${COMPONENTS[@]}"; do
    gen_script="./$component/.generate.sh"
    
    if [[ ! -f "$gen_script" ]]; then
        log_error "Generate script not found: $gen_script"
        ((FAILED++))
        FAILED_COMPONENTS+=("$component")
        continue
    fi
    
    log_info "Processing: $component"
    if bash "$gen_script"; then
        log_info "  ✓ $component"
    else
        log_error "  ✗ $component failed"
        ((FAILED++))
        FAILED_COMPONENTS+=("$component")
    fi
done

# Handle special/static components that don't regenerate (upstream sources)
log_section "Handling External/Static Components"

log_info "Syncing MariaDB Dockerfiles from upstream..."
if bash -c '
    set -e
    curl --fail -s https://raw.githubusercontent.com/MariaDB/mariadb-docker/master/10.11/Dockerfile -o mariadb/Dockerfile.ubuntu
    curl --fail -s https://raw.githubusercontent.com/MariaDB/mariadb-docker/master/10.11/docker-entrypoint.sh -o mariadb/docker-entrypoint.sh
    curl --fail -s https://raw.githubusercontent.com/MariaDB/mariadb-docker/master/10.11/healthcheck.sh -o mariadb/healthcheck.sh

    # Create debian variant
    cp mariadb/Dockerfile.ubuntu mariadb/Dockerfile.debian
    chmod +x mariadb/docker-entrypoint.sh

    # Customize for our setup
    sed -i "s|FROM ubuntu:jammy|FROM eilandert/ubuntu-base:rolling\nCOPY bootstrap.sh /|" mariadb/Dockerfile.ubuntu
    sed -i "s|FROM ubuntu:jammy|FROM eilandert/debian-base:stable\nCOPY bootstrap.sh /|" mariadb/Dockerfile.debian
    sed -i "s|jammy|noble|g" mariadb/Dockerfile.ubuntu
    sed -i "s|jammy|bookworm|g" mariadb/Dockerfile.debian
    sed -i "s|repo/ubuntu|repo/debian|g" mariadb/Dockerfile.debian
    sed -i "s|ubu2004|ubu2204|g" mariadb/Dockerfile.ubuntu
    sed -i "s|ubu2204|deb12|g" mariadb/Dockerfile.debian
'; then
    log_info "  ✓ MariaDB"
else
    log_error "  ✗ MariaDB sync failed"
    ((FAILED++))
    FAILED_COMPONENTS+=("mariadb-upstream")
fi

# Get roundcube version if available
if command -v lastversion &> /dev/null; then
    log_info "Checking Roundcube version..."
    if LASTVERSION=$(lastversion -b 1.6 https://github.com/roundcube/roundcubemail/ 2>/dev/null); then
        if [[ -n "$LASTVERSION" ]]; then
            echo "$LASTVERSION" > roundcube/.lastversion
            log_info "  Roundcube version: $LASTVERSION"
        fi
    fi
else
    log_info "  lastversion not installed, skipping version check"
fi

# Git commit all changes
log_section "Committing Changes"

if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
    log_info "Staging generated files..."
    git add -A base/ php-fpm/ apache-phpfpm/ nginx/ angie/ mariadb/ roundcube/.lastversion 2>/dev/null || true
    
    log_info "Committing..."
    git commit -m "autogenerated: dockerfile generation from templates" || log_error "Git commit failed"
    
    log_info "Pushing..."
    git push || log_error "Git push failed (may need credentials)"
else
    log_info "No changes to commit"
fi

# Summary
log_section "Generation Complete"
if [[ $FAILED -eq 0 ]]; then
    echo -e "${GREEN}✓ All components generated successfully${NC}"
    exit 0
else
    echo -e "${RED}✗ Failed components: ${FAILED_COMPONENTS[*]}${NC}"
    exit 1
fi


