# syntax=docker/dockerfile:1.7
FROM    eilandert/debian-base:stable
LABEL org.opencontainers.image.authors="eilandert"
LABEL org.opencontainers.image.source="https://github.com/eilandert/dockerized"

LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"

COPY main.py /root/warmup_sitemaps/main.py
COPY requirements.txt /root/warmup_sitemaps/requirements.txt

RUN    apt-get -y update \
    && apt-get --no-install-recommends install -y python3-pip \
    && pip3 install --break-system-packages --upgrade -r /root/warmup_sitemaps/requirements.txt \
    && chmod 755 /root/warmup_sitemaps/main.py \
        && apt-get -y autoremove \
    && apt-get -y autoclean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /root/.cache

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 CMD test -f /tmp/healthy && find /tmp/healthy -mmin -10 | grep -q . || exit 1

ENTRYPOINT ["/root/warmup_sitemaps/main.py"]
