FROM eilandert/debian-base:stable
LABEL maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
ENV     LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libmimalloc-secure.so

COPY bootstrap.sh /bootstrap.sh

RUN apt-get -y update ;\
    apt-get --no-install-recommends -y install \
      rspamd \
      syslog-ng-core \
    ;\
    mkdir -p /etc/rspamd/override.d/ ;\
    echo 'type = "console";' > /etc/rspamd/override.d/logging.inc ;\
    echo 'bind_socket = "*:11334";' > /etc/rspamd/override.d/worker-controller.inc ;\
    echo 'pidfile = false;' > /etc/rspamd/override.d/options.inc ;\
    mv /etc/rspamd /etc/rspamd.orig ;\
    mkdir -p /var/log/rspamd ;\
    mkdir -p /var/lib/rspamd ;\
    mkdir -p /var/run/rspamd ;\
    rm -rf /usr/local/share/man /usr/local/share/games /usr/local/share/include /usr/local/share/src /usr/local/lib/python3.8 /usr/local/sbin ;\
    apt-get -y autoremove ;\
    apt-get -y clean autoclean ;\
    rm -rf /var/lib/apt/lists/* ;\
    chmod +x /bootstrap.sh

COPY syslog-ng.conf /etc/syslog-ng

CMD ["/bootstrap.sh"]

EXPOSE 11332 11333 11334
VOLUME  [ "/var/lib/rspamd" ]
