FROM    eilandert/php-fpm:deb-8.2
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"

COPY    bootstrap.sh /bootstrap.sh

RUN set -ex ;\
    #TEMPLATE4#;\
    #TEMPLATE5#;\
    apt-get update ;\
    apt-get -y upgrade ;\
    apt-get -y --no-install-recommends install \
      brotli \
      curl \
      fcgiwrap \
      geoip-bin \
      libjemalloc2 \
      lua-resty \
      mimalloc \
      modsecurity-crs \
      nginx-full \
      ssl-cert \
      zstd \
      libnginx-mod-ssl-ct \
      libnginx-mod-http-ssl-ct \
      libnginx-mod-stream-ssl-ct \
    ;\
    apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* ;\
    mv /etc/nginx /etc/nginx.orig && mkdir -p /etc/nginx ;\
    mv /etc/modsecurity /etc/modsecurity.orig && mkdir -p /etc/modsecurity ;\
    chmod +x /bootstrap.sh ;\
    rm -f /var/spool/nullmailer/trigger ;\
    echo "background_thread:true,metadata_thp:auto" > /etc/malloc.conf

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443

WORKDIR /etc/nginx
