FROM    python:slim-bookworm
LABEL org.opencontainers.image.authors="eilandert"
LABEL org.opencontainers.image.source="https://github.com/eilandert/dockerized"

LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"

# Install OS and Python dependencies
RUN set -x ;\
    apt update ;\
    apt-get install --no-install-recommends -y git ;\
    apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* ;\
    pip install --upgrade pip setuptools wheel ;\
    pip install numpy Pillow opencv-python-headless onnxruntime --no-cache-dir --force-reinstall --ignore-requires-python ;\
    pip install ddddocr==1.5.6 --no-cache-dir --force-reinstall --ignore-requires-python

# Clone repo by latest tag and set up
RUN git clone --branch $(git ls-remote --tags --sort="v:refname" https://github.com/whiteout-project/bot | tail -n1 | sed 's/.*\///; s/\^{}//') --single-branch https://github.com/whiteout-project/bot.git app ;\
    cd /app ;\
    echo 0 > bot_token.txt ;\
    python main.py --autoupdate ;\
    rm bot_token.txt

# Copy bootstrap script and prepare
COPY bootstrap.sh /bootstrap.sh
RUN chmod +x /bootstrap.sh

WORKDIR /app
ENTRYPOINT ["/bootstrap.sh"]
