# syntax=docker/dockerfile:1.7
# This file might be outdated, see https://github.com/eilandert/dockerized for a recent one
FROM eilandert/debian-base:stable
LABEL   org.opencontainers.image.authors="eilandert" \
        org.opencontainers.image.source="https://github.com/eilandert/dockerized" \
        maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"
COPY --chmod=0755 bootstrap.sh /bootstrap.sh
COPY    syslog-ng.conf /etc/syslog-ng

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -ex ;\
    rm -f /etc/apt/apt.conf.d/docker-clean ;\
    apt-get update ;\
    apt-get install -y --no-install-recommends nullmailer mailutils ;\
    apt-get -y --no-install-recommends install \
      dovecot-core \
      dovecot-imapd \
      dovecot-lmtpd \
      dovecot-managesieved \
      dovecot-mysql \
      dovecot-pgsql \
      dovecot-pop3d \
      dovecot-sieve \
      dovecot-submissiond \
      syslog-ng-core \
      libfilesys-diskspace-perl \
      libfilesys-diskusage-perl \
      libdbd-pgsql \
      libdbd-mysql-perl \
      libdbd-mysql \
      libdbd-mariadb-perl \
      pyzor \
      openssl \
      razor \
      rspamd \
      spamc \
      curl \
      mimalloc \
      libjemalloc2 ;\
    mkdir -p /opt/scripts/vimbadmin.orig ;\
    curl -fSL https://github.com/gibzer/vimbadmin-perl/archive/master.tar.gz |\
      tar xz --strip-components=1 -C /opt/scripts/vimbadmin.orig ;\
    rm -f /opt/scripts/vimbadmin.orig/*.deb ;\
    apt-get -y purge curl ;\
    apt-get -y autoremove ;\
    mv /etc/dovecot /etc/dovecot.orig && mkdir -p /etc/dovecot ;\
    addgroup --gid 5000 vmail ;\
    useradd -u 5000 -g 5000 -s /sbin/nologin vmail ;\
    echo "background_thread:true,metadata_thp:auto" > /etc/malloc.conf

WORKDIR /etc/dovecot

EXPOSE 24 143 110 993 995 4190

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 CMD pgrep -x dovecot > /dev/null && doveadm who -1 > /dev/null 2>&1 || exit 1

CMD ["/bootstrap.sh"]
