FROM    eilandert/php-fpm:deb-8.2
LABEL org.opencontainers.image.authors="eilandert"
LABEL org.opencontainers.image.source="https://github.com/eilandert/dockerized"

LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"

COPY    bootstrap.sh /bootstrap.sh

RUN set -ex ;\
    echo "deb [trusted=yes] http://deb.myguard.nl:8888 ${DIST} main" > /etc/apt/sources.list.d/deb.myguard.nl.list ;\
    #TEMPLATE4# ;\
    #TEMPLATE5# ;\
    apt-get update ;\
    apt-get -y upgrade

RUN apt-get -y --no-install-recommends install \
      brotli \
      curl \
      fcgiwrap \
      geoip-bin \
      libjemalloc2 \
      lua-http \
      lua-socket \
      lua-zlib \
      lua-resty \
      mimalloc \
      modsecurity-crs \
      angie-full \
      openssl \
      ssl-cert \
      zstd ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/

RUN mv /etc/angie /etc/angie.orig ;\
    mv /etc/modsecurity /etc/modsecurity.orig ;\
    mkdir -p /etc/angie ;\
    mkdir -p /etc/modsecurity ;\
    chmod +x /bootstrap.sh ;\
    rm -f /var/spool/nullmailer/trigger
WORKDIR /etc/angie
EXPOSE  443/udp
EXPOSE  443 443
EXPOSE  80 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD curl -f http://localhost/ || exit 1

CMD     ["/bootstrap.sh"]

