FROM    eilandert/php-fpm:7.4
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"

COPY    bootstrap.sh /bootstrap.sh

RUN set -ex ;\
    echo "deb [trusted=yes] http://deb.myguard.nl:8888 ${DIST} main" > /etc/apt/sources.list.d/deb.myguard.nl.list ;\
    #TEMPLATE4# ;\
    #TEMPLATE5# ;\
    apt-get update ;\
    apt-get -y upgrade 

RUN apt-get -y --no-install-recommends install \
      brotli \
      curl \
      fcgiwrap \
      geoip-bin \
      libjemalloc2 \
      lua-http \
      lua-socket \
      lua-zlib \
      lua-resty \
      mimalloc \
      modsecurity-crs \
      nginx-full \
      openssl \
      ssl-cert \
      zstd ;\
    apt-get -y autoremove && apt-get -y autoclean ;\
    rm -rf /var/lib/apt/lists/

RUN mv /etc/nginx /etc/nginx.orig ;\
    mv /etc/modsecurity /etc/modsecurity.orig ;\
    mkdir -p /etc/nginx ;\
    mkdir -p /etc/modsecurity ;\
    chmod +x /bootstrap.sh ;\
    rm -f /var/spool/nullmailer/trigger

CMD     ["/bootstrap.sh"]
EXPOSE  80 80
EXPOSE  443 443
EXPOSE  443/udp

WORKDIR /etc/nginx
