# This file might be outdated, see https://github.com/eilandert/dockerized/tree/master/base for a recent one
FROM    ubuntu:hirsute
LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"

COPY    bootstrap.sh /bootstrap.sh
COPY    deb.paranoid.nl.gpg /etc/apt/trusted.gpg.d/deb.paranoid.nl.gpg
COPY    ondrej-ubuntu-php.gpg /etc/apt/trusted.gpg.d/ondrej-ubuntu-php.gpg

# prefer install latest packages from my own repository on https://deb.paranoid.nl
RUN set -x ;\
    . /etc/os-release ;\
    apt-get -y update ;\
    apt-get install -y --no-install-recommends ca-certificates ;\
    echo "deb [arch=amd64] http://deb.paranoid.nl ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/deb.paranoid.nl.list ;\
    echo "deb [trusted=yes] http://ppa.launchpad.net/ondrej/php/ubuntu/ ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/ondrej-ppa.list ;\
    { \
	echo 'Package: *'; \
	echo 'Pin: release a=${VERSION_CODENAME}-backports'; \
	echo 'Pin-Priority: 900'; \
    } > /etc/apt/preferences.d/99backports ;\
    { \
        echo 'Package: *'; \
        echo 'Pin: origin deb.paranoid.nl'; \
        echo 'Pin-Priority: 901'; \
    } > /etc/apt/preferences.d/99myguard ;\
    apt-get -y update ;\
    apt-get install -y --no-install-recommends ca-certificates tzdata openssl libssl1.1 libssl-dev libjemalloc2 ;\
    apt-get -y update ;\    
    apt-get -y upgrade ;\
    apt-get -y clean ;\
    apt-get -y autoremove ;\
    apt-get -y autoclean ;\
    chmod +x /bootstrap.sh ;\
    sh -x ;\
    for user in games lp news uucp proxy list irc gnats backup; do deluser -q $user && delgroup -q $user; done ;\
    for user in `awk -F: '($3 < 1000) {print $1 }' /etc/passwd`; do \
        if [ $user != "root" ]; then \
            usermod -L $user && usermod -s /usr/sbin/nologin $user ;\
        fi ;\
    done ;\
    #	  for file in `ls /usr/bin/apt*`; do dpkg-statoverride --update --add root adm 0500 $file; done ;\
    #	  for file in `ls /usr/bin/deb*`; do dpkg-statoverride --update --add root adm 0500 $file; done ;\
    #     for file in `ls /usr/bin/dpkg*`; do dpkg-statoverride --update --add root adm 0500 $file; done ;\
    for file in `ls /usr/sbin/e2*`; do dpkg-statoverride --update --add root adm 0000 $file; done ;\
    for file in `ls /usr/sbin/fsck*`; do dpkg-statoverride --update --add root adm 0000 $file; done ;\
    for file in `ls /usr/sbin/mk*`; do dpkg-statoverride --update --add root adm 0000 $file; done ;\
    for file in `ls /usr/sbin/swap*`; do dpkg-statoverride --update --add root adm 0000 $file; done ;\
    dpkg-statoverride --update --add root adm 0000 /bin/dmesg ;\
    dpkg-statoverride --update --add root adm 0000 /sbin/badblocks ;\
    dpkg-statoverride --update --add root adm 0000 /bin/su ;\
    dpkg-statoverride --add root adm 0000 /usr/bin/sudo ;\
    dpkg-statoverride --add root adm 0500 /usr/bin/ping ;\
    echo 'man-db man-db/auto-update boolean false'|debconf-set-selections ;\
    rm -rf /var/lib/apt/lists/* 


CMD     ["/bootstrap.sh"]
