# This file might be outdated, see https://github.com/eilandert/dockerized for a recent one
FROM eilandert/debian-base:stable
LABEL org.opencontainers.image.authors="eilandert"
LABEL org.opencontainers.image.source="https://github.com/eilandert/dockerized"

LABEL   maintainer="Thijs Eilander <eilander@myguard.nl>"
ENV     DEBIAN_FRONTEND="noninteractive"

COPY    bootstrap.sh /bootstrap.sh
RUN set -ex ;\
    apt-get update ;\
    apt-get -y purge libjemalloc2 ;\
    apt-get -y --no-install-recommends install \
      ca-certificates tzdata openssl syslog-ng \
      redis ;\
    # disable Redis protected mode and bind as it is unnecessary in context of Docker
    # Also, run in foreground and write the errorlog to /dev/stdout
    sed -i s/"^bind\ "/#bind\ / /etc/redis/redis.conf ;\
    sed -i s/"protected-mode yes"/"protected-mode no"/ /etc/redis/redis.conf ;\
    sed -i s/"daemonize yes"/"daemonize no"/ /etc/redis/redis.conf ;\
    sed -i s/"logfile \/var\/log\/redis\/redis-server.log"/"logfile \/dev\/stdout"/ /etc/redis/redis.conf ;\
    mv /etc/redis /etc/redis.orig ;\
    apt-get -y autoremove && apt-get -y autoclean && rm -rf /var/lib/apt/lists/* ;\
    chmod +x /bootstrap.sh
VOLUME ["/var/lib/redis"]
EXPOSE 6379
COPY syslog-ng.conf /etc/syslog-ng

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD redis-cli ping || exit 1

CMD [ "/bootstrap.sh" ]


